// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'downloadPanel': string;
  'episode': string;
  'episodeActions': string;
  'episodeList': string;
  'episodeMain': string;
  'episodeNumber': string;
  'episodeProgress': string;
  'episodeProgressText': string;
  'episodesHeader': string;
  'info': string;
  'labels': string;
  'layout': string;
  'libraryLink': string;
  'noEpisodes': string;
  'overview': string;
  'poster': string;
  'queuedNote': string;
  'rangeInput': string;
  'rangeRow': string;
  'release': string;
  'releaseList': string;
  'releaseTitle': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
