// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'grid': string;
  'libraryCount': string;
  'message': string;
  'resultCount': string;
  'searchIcon': string;
  'searchInput': string;
  'searchRow': string;
  'siteTab': string;
  'siteTabActive': string;
  'siteTabs': string;
}
export const cssExports: CssExports;
export default cssExports;
