// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'content': string;
  'labels': string;
  'poster': string;
  'posterContainer': string;
  'posterPlaceholder': string;
  'title': string;
  'underlay': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
