// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'right': string;
  'row': string;
  'rowBottom': string;
  'rowTop': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
